# List of dependecies for CSI attacher

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

#[[constraint]]
#  name = "github.com/golang/mock"
#  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-csi/csi-test"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0-beta.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0-beta.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"
