# List of dependecies for CSI attacher

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.15"

[prune]
   non-go = true
   go-tests = true
   unused-packages = true
